### ISSUE TITLE
Will you share the PDF of the paper?

### ISSUE THREAD

**Issue by GoingMyWay** [thomyphan/resilient-marl#1]
Hi, could you please share the PDF of the paper?

**Comment by thomyphan** [comment]
Hi, thank you for your interest in our paper. It has just been published in the proceedings and can be freely accessed at https://ojs.aaai.org/index.php/AAAI/article/view/17348/17155

**Comment by GoingMyWay** [comment]
> Hi, thank you for your interest in our paper. It has just been published in the proceedings and can be freely accessed at https://ojs.aaai.org/index.php/AAAI/article/view/17348/17155

Great. Thank you.
